const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  purge: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    borderRadius: {
      'none': 'var(--border-radius-none)',
      'sm': 'var(--border-radius-sm)',
      'DEFAULT': 'var(--border-radius)',
      'md': 'var(--border-radius-md)',
      'lg': 'var(--border-radius-lg)',
      'xl': 'var(--border-radius-xl)',
      '2xl': 'var(--border-radius-2xl)',
      '3xl': 'var(--border-radius-3xl)',
      'full': 'var(--border-radius-full)',
    },
    boxShadow: {
      'xs': 'var(--box-shadow-xs)',
      'sm': 'var(--box-shadow-sm)',
      'default': ' var(--box-shadow-default)',
      'md': 'var(--box-shadow-md)',
      'lg': ' var(--box-shadow-lg)',
      'xl': ' var(--box-shadow-xl)',
      '2xl': 'var(--box-shadow-2xl)',
      'inner': 'var(--box-shadow-inner)',
      'outline': 'var(--box-shadow-outline)',
      'none': 'var(--box-shadow-none)'
    },
    spacing: {
      'px': 'var(--spacing-px)',
      '0': 'var(--spacing-0)',
      '0.5': 'var(--spacing-0-5)',
      '1': 'var(--spacing-1)',
      '1.5': 'var(--spacing-1-5)',
      '2': 'var(--spacing-2)',
      '2.5': 'var(--spacing-2-5)',
      '3': 'var(--spacing-3)',
      '3.5': 'var(--spacing-3-5)',
      '4': 'var(--spacing-4)',
      '5': 'var(--spacing-5)',
      '6': 'var(--spacing-6)',
      '7': 'var(--spacing-7)',
      '8': 'var(--spacing-8)',
      '9': 'var(--spacing-9)',
      '10': 'var(--spacing-10)',
      '11': 'var(--spacing-11)',
      '12': 'var(--spacing-12)',
      '14': 'var(--spacing-14)',
      '16': 'var(--spacing-16)',
      '20': 'var(--spacing-20)',
      '24': 'var(--spacing-24)',
      '28': 'var(--spacing-28)',
      '32': 'var(--spacing-32)',
      '36': 'var(--spacing-36)',
      '40': 'var(--spacing-40)',
      '44': 'var(--spacing-44)',
      '48': 'var(--spacing-48)',
      '52': 'var(--spacing-52)',
      '56': 'var(--spacing-56)',
      '60': 'var(--spacing-60)',
      '64': 'var(--spacing-64)',
      '72': 'var(--spacing-72)',
      '80': 'var(--spacing-80)',
      '96': 'var(--spacing-96)',
      'sm': 'var(--spacing-sm)',
      'md': 'var(--spacing-md)',
      'lg': 'var(--spacing-lg)',
      'xl': 'var(--spacing-xl)'
    },
    borderStyle: {
      'solid': 'var(--border-style-solid)',
      'dashed': 'var(--border-style-dashed)',
      'dotted': ' var(--border-style-dotted)',
      'double': 'var(--border-style-double)',
      'none': ' var(--border-style-none)',
      'foo': ' var(--border-style-foo)',
    },
    fontFamily: {
      'display': 'var(--font-display)',
      'body': 'var(--font-body)',
    },
    fontWeights: {
      'thin': 'var(--font-weight-thin)',
      'extralight': 'var(--font-weight-extralight)',
      'light': 'var(--font-weight-light)',
      'normal': 'var(--font-weight-normal)',
      'medium': 'var(--font-weight-medium)',
      'semibold': 'var(--font-weight-semibold)',
      'bold': 'var(--font-weight-bold)',
      'extrabold': 'var(--font-weight-extrabold)',
      'black': 'var(--font-weight-black)',
  },

    //  'Inter var', ...defaultTheme.fontFamily.sans

    textColor: {
      black: 'var(--color-text-black)',
      white: 'var(--color-text-white)',
      gray: {
        50: 'var(--color-text-gray-50)',
        100: 'var(--color-text-gray-100)',
        200: 'var(--color-text-gray-200)',
        300: 'var(--color-text-gray-300)',
        400: 'var(--color-text-gray-400)',
        500: 'var(--color-text-gray-500)',
        600: 'var(--color-text-gray-600)',
        700: 'var(--color-text-gray-700)',
        800: 'var(--color-text-gray-800)',
        900: 'var(--color-text-gray-900)',
      },
      red: {
        50: 'var(--color-text-red-50)',
        100: 'var(--color-text-red-100)',
        200: 'var(--color-text-red-200)',
        300: 'var(--color-text-red-300)',
        400: 'var(--color-text-red-400)',
        500: 'var(--color-text-red-500)',
        600: 'var(--color-text-red-600)',
        700: 'var(--color-text-red-700)',
        800: 'var(--color-text-red-800)',
        900: 'var(--color-text-red-900)',
      },
      yellow: {
        50: 'var(--color-text-yellow-50)',
        100: 'var(--color-text-yellow-100)',
        200: 'var(--color-text-yellow-200)',
        300: 'var(--color-text-yellow-300)',
        400: 'var(--color-text-yellow-400)',
        500: 'var(--color-text-yellow-500)',
        600: 'var(--color-text-yellow-600)',
        700: 'var(--color-text-yellow-700)',
        800: 'var(--color-text-yellow-800)',
        900: 'var(--color-text-yellow-900)',
      },
      green: {
        50: 'var(--color-text-green-50)',
        100: 'var(--color-text-green-100)',
        200: 'var(--color-text-green-200)',
        300: 'var(--color-text-green-300)',
        400: 'var(--color-text-green-400)',
        500: 'var(--color-text-green-500)',
        600: 'var(--color-text-green-600)',
        700: 'var(--color-text-green-700)',
        800: 'var(--color-text-green-800)',
        900: 'var(--color-text-green-900)',
      },
      blue: {
        50: 'var(--color-text-blue-50)',
        100: 'var(--color-text-blue-100)',
        200: 'var(--color-text-blue-200)',
        300: 'var(--color-text-blue-300)',
        400: 'var(--color-text-blue-400)',
        500: 'var(--color-text-blue-500)',
        600: 'var(--color-text-blue-600)',
        700: 'var(--color-text-blue-700)',
        800: 'var(--color-text-blue-800)',
        900: 'var(--color-text-blue-900)',
      },
      indigo: {
        50: 'var(--color-text-indigo-50)',
        100: 'var(--color-text-indigo-100)',
        200: 'var(--color-text-indigo-200)',
        300: 'var(--color-text-indigo-300)',
        400: 'var(--color-text-indigo-400)',
        500: 'var(--color-text-indigo-500)',
        600: 'var(--color-text-indigo-600)',
        700: 'var(--color-text-indigo-700)',
        800: 'var(--color-text-indigo-800)',
        900: 'var(--color-text-indigo-900)',
      },
      purple: {
        50: 'var(--color-text-purple-50)',
        100: 'var(--color-text-purple-100)',
        200: 'var(--color-text-purple-200)',
        300: 'var(--color-text-purple-300)',
        400: 'var(--color-text-purple-400)',
        500: 'var(--color-text-purple-500)',
        600: 'var(--color-text-purple-600)',
        700: 'var(--color-text-purple-700)',
        800: 'var(--color-text-purple-800)',
        900: 'var(--color-text-purple-900)',
      },
      pink: {
        50: 'var(--color-text-pink-50)',
        100: 'var(--color-text-pink-100)',
        200: 'var(--color-text-pink-200)',
        300: 'var(--color-text-pink-300)',
        400: 'var(--color-text-pink-400)',
        500: 'var(--color-text-pink-500)',
        600: 'var(--color-text-pink-600)',
        700: 'var(--color-text-pink-700)',
        800: 'var(--color-text-pink-800)',
        900: 'var(--color-text-pink-900)',
      },
    },
    backgroundColor: {
      white: 'var(--color-bg-white)',
      gray: {
        50: 'var(--color-bg-gray-50)',
        100: 'var(--color-bg-gray-100)',
        200: 'var(--color-bg-gray-200)',
        300: 'var(--color-bg-gray-300)',
        400: 'var(--color-bg-gray-400)',
        500: 'var(--color-bg-gray-500)',
        600: 'var(--color-bg-gray-600)',
        700: 'var(--color-bg-gray-700)',
        800: 'var(--color-bg-gray-800)',
        900: 'var(--color-bg-gray-900)',
      },
      red: {
        50: 'var(--color-bg-red-50)',
        100: 'var(--color-bg-red-100)',
        200: 'var(--color-bg-red-200)',
        300: 'var(--color-bg-red-300)',
        400: 'var(--color-bg-red-400)',
        500: 'var(--color-bg-red-500)',
        600: 'var(--color-bg-red-600)',
        700: 'var(--color-bg-red-700)',
        800: 'var(--color-bg-red-800)',
        900: 'var(--color-bg-red-900)',
      },
      yellow: {
        50: 'var(--color-bg-yellow-50)',
        100: 'var(--color-bg-yellow-100)',
        200: 'var(--color-bg-yellow-200)',
        300: 'var(--color-bg-yellow-300)',
        400: 'var(--color-bg-yellow-400)',
        500: 'var(--color-bg-yellow-500)',
        600: 'var(--color-bg-yellow-600)',
        700: 'var(--color-bg-yellow-700)',
        800: 'var(--color-bg-yellow-800)',
        900: 'var(--color-bg-yellow-900)',
      },
      green: {
        50: 'var(--color-bg-green-50)',
        100: 'var(--color-bg-green-100)',
        200: 'var(--color-bg-green-200)',
        300: 'var(--color-bg-green-300)',
        400: 'var(--color-bg-green-400)',
        500: 'var(--color-bg-green-500)',
        600: 'var(--color-bg-green-600)',
        700: 'var(--color-bg-green-700)',
        800: 'var(--color-bg-green-800)',
        900: 'var(--color-bg-green-900)',
      },
      blue: {
        50: 'var(--color-bg-blue-50)',
        100: 'var(--color-bg-blue-100)',
        200: 'var(--color-bg-blue-200)',
        300: 'var(--color-bg-blue-300)',
        400: 'var(--color-bg-blue-400)',
        500: 'var(--color-bg-blue-500)',
        600: 'var(--color-bg-blue-600)',
        700: 'var(--color-bg-blue-700)',
        800: 'var(--color-bg-blue-800)',
        900: 'var(--color-bg-blue-900)',
      },
      indigo: {
        50: 'var(--color-bg-indigo-50)',
        100: 'var(--color-bg-indigo-100)',
        200: 'var(--color-bg-indigo-200)',
        300: 'var(--color-bg-indigo-300)',
        400: 'var(--color-bg-indigo-400)',
        500: 'var(--color-bg-indigo-500)',
        600: 'var(--color-bg-indigo-600)',
        700: 'var(--color-bg-indigo-700)',
        800: 'var(--color-bg-indigo-800)',
        900: 'var(--color-bg-indigo-900)',
      },
      purple: {
        50: 'var(--color-bg-purple-50)',
        100: 'var(--color-bg-purple-100)',
        200: 'var(--color-bg-purple-200)',
        300: 'var(--color-bg-purple-300)',
        400: 'var(--color-bg-purple-400)',
        500: 'var(--color-bg-purple-500)',
        600: 'var(--color-bg-purple-600)',
        700: 'var(--color-bg-purple-700)',
        800: 'var(--color-bg-purple-800)',
        900: 'var(--color-bg-purple-900)',
      },
      pink: {
        50: 'var(--color-bg-pink-50)',
        100: 'var(--color-bg-pink-100)',
        200: 'var(--color-bg-pink-200)',
        300: 'var(--color-bg-pink-300)',
        400: 'var(--color-bg-pink-400)',
        500: 'var(--color-bg-pink-500)',
        600: 'var(--color-bg-pink-600)',
        700: 'var(--color-bg-pink-700)',
        800: 'var(--color-bg-pink-800)',
        900: 'var(--color-bg-pink-900)',
      },


      animation: {
        'none': 'none',
        'spin': 'spin 1s linear infinite',
        'ping': 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
        'pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce': 'bounce 1s infinite'
      },
  

  




      
    },
    extend: {
      // fontFamily: {
      //   sans: ['Inter var', ...defaultTheme.fontFamily.sans],
      // },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/typography', '@ui-devtools/tailwind/babel', '@tailwindcss/forms'),
  ],
};